# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI-CD

on:
  push:
    branches: [ "main" ]
    paths-ignore: ["README.md"]
  pull_request:
    branches: [ "main" ]
env:
  AZURE_RG: RG2
  AZURE_SUBSCRIPTION: eab8e5e8-8d87-4cce-b7db-8abda8247d72
  AZURE-LOCATION: WestEurope
jobs:
  Build-Job:
    runs-on: ubuntu-latest
    env:
      configuration: release
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.configuration }}
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration ${{ env.configuration }}
      - name: Publish 
        run: dotnet publish --configuration ${{ env.configuration }} --output ${{runner.temp }}/publish
